### PR TITLE
`extraDependencies` for `createQuery` and `createJsonQuery`

### PR DESCRIPTION
**Pull request by NazariiShvets**
fixes: https://github.com/igorkamyshev/farfetched/issues/350

### CODE REVIEW

**Review by igorkamyshev — CHANGES_REQUESTED** [review]
Thanks for contribution 😇

1. I am not sure if this change is good. Let's finish discussion in the issue first.
2. We do not accept any features without docs and changesets. Please, refer to the contributions guide in the readme.

**Comment by NazariiShvets** [comment]
There is no way to provide custom `sourced` fields using `createQuery` and `createJsonQuery`. It PR allows to pass stores as relation for query to handle `sourced` fields relation side-effects

**Comment by igorkamyshev** [comment]
Check internal implementation of createQuery. You can write something like this in your code.

**Comment by NazariiShvets** [comment]
Sure

I also can fork whole farfetched to my codebase if i need 1 simple extra parameter. But i dont want all of that complexity and extra maintaining cost for new releases, so i decided to contribute to main repo

If u think its wrong fit just say it and close PR/issue. I will found a way to deal with my cases in my codebase instead

**Comment by igorkamyshev** [comment]
Sorry, without strong motivation and any documentation I simply do not get why this feature has to be in core.

Please, provide proper RFC and documentation and reopen PR with it 🙏

**Pull request closed without merging**
